POPULATION_SIZE = 2
MUTATION_RANGE = 0.05
MAX_GENERATIONS = 500
NUMBER_OF_DAYS = 5
NUMBER_OF_CLASSROOMS = 5  
MAX_TIME_IN_CLASSROOM = 720 #time in minutes between 07:00 - 19:00
MIN_PAUSE_TIME = 15
MIN_NUMBER_OF_LECTURES = 3
AVERAGE_LECTURE_DURATION = 96 #average duration of lecture is (30+60+90+120+180) / 5 = 96 minutes
MAX_TIME_BEFORE_FIRST_CLASS = MAX_TIME_IN_CLASSROOM - (MIN_NUMBER_OF_LECTURES * AVERAGE_LECTURE_DURATION + (MIN_NUMBER_OF_LECTURES - 1) * MIN_PAUSE_TIME)
MAX_ATTEMPTS = 100
                                    
                                    
                                  
