from utils import calculate_ald
from data_handler import read_lectures

POPULATION_SIZE = 100
MUTATION_RANGE = 0.05
MAX_GENERATIONS = 1000
NUMBER_OF_DAYS = 5
NUMBER_OF_CLASSROOMS = 5  
MAX_TIME_IN_CLASSROOM = 720 #time in minutes between 07:00 - 19:00
MIN_PAUSE_TIME = 15
MIN_NUMBER_OF_LECTURES = 2
AVERAGE_LECTURE_DURATION = int(calculate_ald(read_lectures()))
MAX_TIME_BEFORE_FIRST_CLASS = MAX_TIME_IN_CLASSROOM - (MIN_NUMBER_OF_LECTURES * AVERAGE_LECTURE_DURATION + (MIN_NUMBER_OF_LECTURES - 1) * MIN_PAUSE_TIME)
MAX_ATTEMPTS = 100
CROSSOVER_ATTEMPTS = 50
MUTATION_ATTEMPTS = 15      
DEDUCTED_FITNESS = 300
                                    
                                  
