from helpers import calculate_ald
from data_handler import read_lectures

STAGNATION_THRESHOLD = 10                 
SHAKEUP_RATIO = 0.9   
POPULATION_SIZE = 100
MUTATION_RANGE = 0.3
ELITISM_RATE = 10
MAX_GENERATIONS = 500
NUMBER_OF_DAYS = 5
NUMBER_OF_CLASSROOMS = 5  
MAX_TIME_IN_CLASSROOM = 720 #time in minutes between 07:00 - 19:00
MIN_PAUSE_TIME = 15
MIN_NUMBER_OF_LECTURES = 2
AVERAGE_LECTURE_DURATION = int(calculate_ald(read_lectures()))
MAX_TIME_BEFORE_FIRST_CLASS = MAX_TIME_IN_CLASSROOM - (MIN_NUMBER_OF_LECTURES * AVERAGE_LECTURE_DURATION + (MIN_NUMBER_OF_LECTURES - 1) * MIN_PAUSE_TIME)
MAX_ATTEMPTS = 100
CROSSOVER_ATTEMPTS = 50
MUTATION_ATTEMPTS = 15      
DEDUCTED_FITNESS = 300
NUM_OF_LECTURES = 60
MUTATION_RATE_PER_CHROMOSOME = 6
                                    
                                  
